In [1]:
import pandas as pd

In [2]:
from sklearn.ensemble import RandomForestClassifier

In [3]:
dataset = pd.read_excel('./iris.xlsx')

In [4]:
dataset.head()

   sepal length  sepal width  petal length  petal width           class
0           7.2          3.6           6.1          2.5  Iris-virginica
1           6.3          3.3           6.0          2.5  Iris-virginica
2           6.7          3.3           5.7          2.5  Iris-virginica
3           6.3          3.4           5.6          2.4  Iris-virginica
4           6.7          3.1           5.6          2.4  Iris-virginica

In [5]:
# Select Data For Predications
x = dataset.iloc[:,:-1]
x

     sepal length  sepal width  petal length  petal width
0             7.2          3.6           6.1          2.5
1             6.3          3.3           6.0          2.5
2             6.7          3.3           5.7          2.5
3             6.3          3.4           5.6          2.4
4             6.7          3.1           5.6          2.4
..            ...          ...           ...          ...
145           4.9          3.1           1.5          0.1
146           4.9          3.1           1.5          0.1
147           4.9          3.1           1.5          0.1
148           4.8          3.0           1.4          0.1
149           4.3          3.0           1.1          0.1

[150 rows x 4 columns]

In [6]:
# Select Data For Predications
y = dataset.loc[:,'class']
y

0      Iris-virginica
1      Iris-virginica
2      Iris-virginica
3      Iris-virginica
4      Iris-virginica
            ...
145       Iris-setosa
146       Iris-setosa
147       Iris-setosa
148       Iris-setosa
149       Iris-setosa
Name: class, Length: 150, dtype: object

In [7]:
# Set Modal Random Forest 
modal = RandomForestClassifier()

Question = Why We Are Choose Fit Method 
✅ fit(x, y):
Model ko input features (x) aur target output (y) ke beech ka relationship sikhane ka training process hota hai.
✅ x:
Input data/features jisse model patterns सीखता है.
✅ y:
Correct output/label jisse model ko sahi answers pata चलते हैं.
✅ fit() bina model:
Model kuch nahi sikhता aur predict nahi kar सकता.
✅ fit() ke baad predict():
Model sikh chuka hota hai aur new data ka result batata है.

In [8]:
# fit modal =>  
modal.fit(x.values,y.values)

RandomForestClassifier()

In [9]:
# predication Data 
predications = modal.predict([[5.5,3.5,1.3,0.2]])

In [10]:
# predication Data 
predications1 =  modal.predict([[5.8,2.6,4,1.2]])

In [11]:
# predication Data 
predications2 =  modal.predict([[7.4,2.8,6.1,1.9]])

In [12]:
# Print Data Of Predication
print(f'The Class Of Iris is - {predications[0]}')

The Class Of Iris is - Iris-setosa

In [13]:
# Print Data Of Predication
print(f'The Class Of Iris is - {predications1[0]}')

The Class Of Iris is - Iris-versicolor

In [14]:
# Print Data Of Predication
print(f'The Class Of Iris is - {predications2[0]}')

The Class Of Iris is - Iris-virginica

# Test Data Predict

In [15]:
data_test_wala = pd.read_excel('./1750577561477-iris-test.xlsx')

In [16]:
data_test_wala.head()

   sepallength  sepalwidth  petallength  petalwidth            class
0          5.4         3.0          4.5         1.5  Iris-versicolor
1          5.3         3.7          1.5         0.2      Iris-setosa
2          5.2         4.1          1.5         0.1      Iris-setosa
3          5.2         3.5          1.5         0.2      Iris-setosa
4          5.2         3.4          1.4         0.2      Iris-setosa

In [17]:
x_test_data = data_test_wala.iloc[:,:-1]
# x_test_data

In [18]:
y_test_data = data_test_wala.loc[:,'class']
# y_test_data

In [19]:
test_modal = RandomForestClassifier()

In [20]:
test_modal.fit(x_test_data.values,y_test_data.values)

RandomForestClassifier()

In [21]:
test_pridication = test_modal.predict(x_test_data.values)

In [22]:
test_pridication

array(['Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa'], dtype=object)